# Estágio de build
FROM node:22-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci --only=production

# Estágio final
FROM node:22-alpine
WORKDIR /app
COPY --from=builder /app/node_modules ./node_modules
COPY . .

RUN mkdir -p /app/Implementacao_Socket_Teste/uploads && \
    chown -R node:node /app/Implementacao_Socket_Teste/uploads

# Configurações de segurança
RUN apk add --no-cache tini
USER node
EXPOSE 3000

ENTRYPOINT ["/sbin/tini", "--"]
CMD ["node", "src/app.js"]